# Generated by Django 4.1.5 on 2023-01-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
