# Generated by Django 4.0.6 on 2023-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='body',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
