# Generated by Django 4.0.6 on 2023-07-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_category_poll_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('poll', 'user'), name='unique_vote'),
        ),
    ]
