# Generated by Django 4.0.6 on 2023-07-09 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polling.polls.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_vote_value_vote_unique_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='creator',
            field=models.ForeignKey(default=polling.polls.utils.get_superuser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
